package com.permissionnanny

/**
 * Cloned from [android.Manifest] v22 because few values such as WRITE_SMS are removed in v23.
 */
class Manifest {

    object permission_group {

        val ACCESSIBILITY_FEATURES = "android.permission-group.ACCESSIBILITY_FEATURES"
        val ACCOUNTS = "android.permission-group.ACCOUNTS"
        val AFFECTS_BATTERY = "android.permission-group.AFFECTS_BATTERY"
        val APP_INFO = "android.permission-group.APP_INFO"
        val AUDIO_SETTINGS = "android.permission-group.AUDIO_SETTINGS"
        val BLUETOOTH_NETWORK = "android.permission-group.BLUETOOTH_NETWORK"
        val BOOKMARKS = "android.permission-group.BOOKMARKS"
        val CALENDAR = "android.permission-group.CALENDAR"
        val CAMERA = "android.permission-group.CAMERA"
        val COST_MONEY = "android.permission-group.COST_MONEY"
        val DEVELOPMENT_TOOLS = "android.permission-group.DEVELOPMENT_TOOLS"
        val DEVICE_ALARMS = "android.permission-group.DEVICE_ALARMS"
        val DISPLAY = "android.permission-group.DISPLAY"
        val HARDWARE_CONTROLS = "android.permission-group.HARDWARE_CONTROLS"
        val LOCATION = "android.permission-group.LOCATION"
        val MESSAGES = "android.permission-group.MESSAGES"
        val MICROPHONE = "android.permission-group.MICROPHONE"
        val NETWORK = "android.permission-group.NETWORK"
        val PERSONAL_INFO = "android.permission-group.PERSONAL_INFO"
        val PHONE_CALLS = "android.permission-group.PHONE_CALLS"
        val SCREENLOCK = "android.permission-group.SCREENLOCK"
        val SOCIAL_INFO = "android.permission-group.SOCIAL_INFO"
        val STATUS_BAR = "android.permission-group.STATUS_BAR"
        val STORAGE = "android.permission-group.STORAGE"
        val SYNC_SETTINGS = "android.permission-group.SYNC_SETTINGS"
        val SYSTEM_CLOCK = "android.permission-group.SYSTEM_CLOCK"
        val SYSTEM_TOOLS = "android.permission-group.SYSTEM_TOOLS"
        val USER_DICTIONARY = "android.permission-group.USER_DICTIONARY"
        val VOICEMAIL = "android.permission-group.VOICEMAIL"
        val WALLPAPER = "android.permission-group.WALLPAPER"
        val WRITE_USER_DICTIONARY = "android.permission-group.WRITE_USER_DICTIONARY"
    }

    object permission {

        val ACCESS_CHECKIN_PROPERTIES = "android.permission.ACCESS_CHECKIN_PROPERTIES"
        val ACCESS_COARSE_LOCATION = "android.permission.ACCESS_COARSE_LOCATION"
        val ACCESS_FINE_LOCATION = "android.permission.ACCESS_FINE_LOCATION"
        val ACCESS_LOCATION_EXTRA_COMMANDS = "android.permission.ACCESS_LOCATION_EXTRA_COMMANDS"
        val ACCESS_MOCK_LOCATION = "android.permission.ACCESS_MOCK_LOCATION"
        val ACCESS_NETWORK_STATE = "android.permission.ACCESS_NETWORK_STATE"
        val ACCESS_SURFACE_FLINGER = "android.permission.ACCESS_SURFACE_FLINGER"
        val ACCESS_WIFI_STATE = "android.permission.ACCESS_WIFI_STATE"
        val ACCOUNT_MANAGER = "android.permission.ACCOUNT_MANAGER"
        val ADD_VOICEMAIL = "com.android.voicemail.permission.ADD_VOICEMAIL"
        val AUTHENTICATE_ACCOUNTS = "android.permission.AUTHENTICATE_ACCOUNTS"
        val BATTERY_STATS = "android.permission.BATTERY_STATS"
        val BIND_ACCESSIBILITY_SERVICE = "android.permission.BIND_ACCESSIBILITY_SERVICE"
        val BIND_APPWIDGET = "android.permission.BIND_APPWIDGET"
        val BIND_CARRIER_MESSAGING_SERVICE = "android.permission.BIND_CARRIER_MESSAGING_SERVICE"
        val BIND_DEVICE_ADMIN = "android.permission.BIND_DEVICE_ADMIN"
        val BIND_DREAM_SERVICE = "android.permission.BIND_DREAM_SERVICE"
        val BIND_INPUT_METHOD = "android.permission.BIND_INPUT_METHOD"
        val BIND_NFC_SERVICE = "android.permission.BIND_NFC_SERVICE"
        val BIND_NOTIFICATION_LISTENER_SERVICE = "android.permission.BIND_NOTIFICATION_LISTENER_SERVICE"
        val BIND_PRINT_SERVICE = "android.permission.BIND_PRINT_SERVICE"
        val BIND_REMOTEVIEWS = "android.permission.BIND_REMOTEVIEWS"
        val BIND_TEXT_SERVICE = "android.permission.BIND_TEXT_SERVICE"
        val BIND_TV_INPUT = "android.permission.BIND_TV_INPUT"
        val BIND_VOICE_INTERACTION = "android.permission.BIND_VOICE_INTERACTION"
        val BIND_VPN_SERVICE = "android.permission.BIND_VPN_SERVICE"
        val BIND_WALLPAPER = "android.permission.BIND_WALLPAPER"
        val BLUETOOTH = "android.permission.BLUETOOTH"
        val BLUETOOTH_ADMIN = "android.permission.BLUETOOTH_ADMIN"
        val BLUETOOTH_PRIVILEGED = "android.permission.BLUETOOTH_PRIVILEGED"
        val BODY_SENSORS = "android.permission.BODY_SENSORS"
        val BRICK = "android.permission.BRICK"
        val BROADCAST_PACKAGE_REMOVED = "android.permission.BROADCAST_PACKAGE_REMOVED"
        val BROADCAST_SMS = "android.permission.BROADCAST_SMS"
        val BROADCAST_STICKY = "android.permission.BROADCAST_STICKY"
        val BROADCAST_WAP_PUSH = "android.permission.BROADCAST_WAP_PUSH"
        val CALL_PHONE = "android.permission.CALL_PHONE"
        val CALL_PRIVILEGED = "android.permission.CALL_PRIVILEGED"
        val CAMERA = "android.permission.CAMERA"
        val CAPTURE_AUDIO_OUTPUT = "android.permission.CAPTURE_AUDIO_OUTPUT"
        val CAPTURE_SECURE_VIDEO_OUTPUT = "android.permission.CAPTURE_SECURE_VIDEO_OUTPUT"
        val CAPTURE_VIDEO_OUTPUT = "android.permission.CAPTURE_VIDEO_OUTPUT"
        val CHANGE_COMPONENT_ENABLED_STATE = "android.permission.CHANGE_COMPONENT_ENABLED_STATE"
        val CHANGE_CONFIGURATION = "android.permission.CHANGE_CONFIGURATION"
        val CHANGE_NETWORK_STATE = "android.permission.CHANGE_NETWORK_STATE"
        val CHANGE_WIFI_MULTICAST_STATE = "android.permission.CHANGE_WIFI_MULTICAST_STATE"
        val CHANGE_WIFI_STATE = "android.permission.CHANGE_WIFI_STATE"
        val CLEAR_APP_CACHE = "android.permission.CLEAR_APP_CACHE"
        val CLEAR_APP_USER_DATA = "android.permission.CLEAR_APP_USER_DATA"
        val CONTROL_LOCATION_UPDATES = "android.permission.CONTROL_LOCATION_UPDATES"
        val DELETE_CACHE_FILES = "android.permission.DELETE_CACHE_FILES"
        val DELETE_PACKAGES = "android.permission.DELETE_PACKAGES"
        val DEVICE_POWER = "android.permission.DEVICE_POWER"
        val DIAGNOSTIC = "android.permission.DIAGNOSTIC"
        val DISABLE_KEYGUARD = "android.permission.DISABLE_KEYGUARD"
        val DUMP = "android.permission.DUMP"
        val EXPAND_STATUS_BAR = "android.permission.EXPAND_STATUS_BAR"
        val FACTORY_TEST = "android.permission.FACTORY_TEST"
        val FLASHLIGHT = "android.permission.FLASHLIGHT"
        val FORCE_BACK = "android.permission.FORCE_BACK"
        val GET_ACCOUNTS = "android.permission.GET_ACCOUNTS"
        val GET_PACKAGE_SIZE = "android.permission.GET_PACKAGE_SIZE"

        @Deprecated("")
        val GET_TASKS = "android.permission.GET_TASKS"
        val GET_TOP_ACTIVITY_INFO = "android.permission.GET_TOP_ACTIVITY_INFO"
        val GLOBAL_SEARCH = "android.permission.GLOBAL_SEARCH"
        val HARDWARE_TEST = "android.permission.HARDWARE_TEST"
        val INJECT_EVENTS = "android.permission.INJECT_EVENTS"
        val INSTALL_LOCATION_PROVIDER = "android.permission.INSTALL_LOCATION_PROVIDER"
        val INSTALL_PACKAGES = "android.permission.INSTALL_PACKAGES"
        val INSTALL_SHORTCUT = "com.android.launcher.permission.INSTALL_SHORTCUT"
        val INTERNAL_SYSTEM_WINDOW = "android.permission.INTERNAL_SYSTEM_WINDOW"
        val INTERNET = "android.permission.INTERNET"
        val KILL_BACKGROUND_PROCESSES = "android.permission.KILL_BACKGROUND_PROCESSES"
        val LOCATION_HARDWARE = "android.permission.LOCATION_HARDWARE"
        val MANAGE_ACCOUNTS = "android.permission.MANAGE_ACCOUNTS"
        val MANAGE_APP_TOKENS = "android.permission.MANAGE_APP_TOKENS"
        val MANAGE_DOCUMENTS = "android.permission.MANAGE_DOCUMENTS"
        val MASTER_CLEAR = "android.permission.MASTER_CLEAR"
        val MEDIA_CONTENT_CONTROL = "android.permission.MEDIA_CONTENT_CONTROL"
        val MODIFY_AUDIO_SETTINGS = "android.permission.MODIFY_AUDIO_SETTINGS"
        val MODIFY_PHONE_STATE = "android.permission.MODIFY_PHONE_STATE"
        val MOUNT_FORMAT_FILESYSTEMS = "android.permission.MOUNT_FORMAT_FILESYSTEMS"
        val MOUNT_UNMOUNT_FILESYSTEMS = "android.permission.MOUNT_UNMOUNT_FILESYSTEMS"
        val NFC = "android.permission.NFC"

        @Deprecated("")
        val PERSISTENT_ACTIVITY = "android.permission.PERSISTENT_ACTIVITY"
        val PROCESS_OUTGOING_CALLS = "android.permission.PROCESS_OUTGOING_CALLS"
        val READ_CALENDAR = "android.permission.READ_CALENDAR"
        val READ_CALL_LOG = "android.permission.READ_CALL_LOG"
        val READ_CONTACTS = "android.permission.READ_CONTACTS"
        val READ_EXTERNAL_STORAGE = "android.permission.READ_EXTERNAL_STORAGE"
        val READ_FRAME_BUFFER = "android.permission.READ_FRAME_BUFFER"
        val READ_HISTORY_BOOKMARKS = "com.android.browser.permission.READ_HISTORY_BOOKMARKS"

        @Deprecated("")
        val READ_INPUT_STATE = "android.permission.READ_INPUT_STATE"
        val READ_LOGS = "android.permission.READ_LOGS"
        val READ_PHONE_STATE = "android.permission.READ_PHONE_STATE"
        val READ_PROFILE = "android.permission.READ_PROFILE"
        val READ_SMS = "android.permission.READ_SMS"

        @Deprecated("")
        val READ_SOCIAL_STREAM = "android.permission.READ_SOCIAL_STREAM"
        val READ_SYNC_SETTINGS = "android.permission.READ_SYNC_SETTINGS"
        val READ_SYNC_STATS = "android.permission.READ_SYNC_STATS"
        val READ_USER_DICTIONARY = "android.permission.READ_USER_DICTIONARY"
        val READ_VOICEMAIL = "com.android.voicemail.permission.READ_VOICEMAIL"
        val REBOOT = "android.permission.REBOOT"
        val RECEIVE_BOOT_COMPLETED = "android.permission.RECEIVE_BOOT_COMPLETED"
        val RECEIVE_MMS = "android.permission.RECEIVE_MMS"
        val RECEIVE_SMS = "android.permission.RECEIVE_SMS"
        val RECEIVE_WAP_PUSH = "android.permission.RECEIVE_WAP_PUSH"
        val RECORD_AUDIO = "android.permission.RECORD_AUDIO"
        val REORDER_TASKS = "android.permission.REORDER_TASKS"

        @Deprecated("")
        val RESTART_PACKAGES = "android.permission.RESTART_PACKAGES"
        val SEND_RESPOND_VIA_MESSAGE = "android.permission.SEND_RESPOND_VIA_MESSAGE"
        val SEND_SMS = "android.permission.SEND_SMS"
        val SET_ACTIVITY_WATCHER = "android.permission.SET_ACTIVITY_WATCHER"
        val SET_ALARM = "com.android.alarm.permission.SET_ALARM"
        val SET_ALWAYS_FINISH = "android.permission.SET_ALWAYS_FINISH"
        val SET_ANIMATION_SCALE = "android.permission.SET_ANIMATION_SCALE"
        val SET_DEBUG_APP = "android.permission.SET_DEBUG_APP"
        val SET_ORIENTATION = "android.permission.SET_ORIENTATION"
        val SET_POINTER_SPEED = "android.permission.SET_POINTER_SPEED"

        @Deprecated("")
        val SET_PREFERRED_APPLICATIONS = "android.permission.SET_PREFERRED_APPLICATIONS"
        val SET_PROCESS_LIMIT = "android.permission.SET_PROCESS_LIMIT"
        val SET_TIME = "android.permission.SET_TIME"
        val SET_TIME_ZONE = "android.permission.SET_TIME_ZONE"
        val SET_WALLPAPER = "android.permission.SET_WALLPAPER"
        val SET_WALLPAPER_HINTS = "android.permission.SET_WALLPAPER_HINTS"
        val SIGNAL_PERSISTENT_PROCESSES = "android.permission.SIGNAL_PERSISTENT_PROCESSES"
        val STATUS_BAR = "android.permission.STATUS_BAR"
        val SUBSCRIBED_FEEDS_READ = "android.permission.SUBSCRIBED_FEEDS_READ"
        val SUBSCRIBED_FEEDS_WRITE = "android.permission.SUBSCRIBED_FEEDS_WRITE"
        val SYSTEM_ALERT_WINDOW = "android.permission.SYSTEM_ALERT_WINDOW"
        val TRANSMIT_IR = "android.permission.TRANSMIT_IR"
        val UNINSTALL_SHORTCUT = "com.android.launcher.permission.UNINSTALL_SHORTCUT"
        val UPDATE_DEVICE_STATS = "android.permission.UPDATE_DEVICE_STATS"
        val USE_CREDENTIALS = "android.permission.USE_CREDENTIALS"
        val USE_SIP = "android.permission.USE_SIP"
        val VIBRATE = "android.permission.VIBRATE"
        val WAKE_LOCK = "android.permission.WAKE_LOCK"
        val WRITE_APN_SETTINGS = "android.permission.WRITE_APN_SETTINGS"
        val WRITE_CALENDAR = "android.permission.WRITE_CALENDAR"
        val WRITE_CALL_LOG = "android.permission.WRITE_CALL_LOG"
        val WRITE_CONTACTS = "android.permission.WRITE_CONTACTS"
        val WRITE_EXTERNAL_STORAGE = "android.permission.WRITE_EXTERNAL_STORAGE"
        val WRITE_GSERVICES = "android.permission.WRITE_GSERVICES"
        val WRITE_HISTORY_BOOKMARKS = "com.android.browser.permission.WRITE_HISTORY_BOOKMARKS"
        val WRITE_PROFILE = "android.permission.WRITE_PROFILE"
        val WRITE_SECURE_SETTINGS = "android.permission.WRITE_SECURE_SETTINGS"
        val WRITE_SETTINGS = "android.permission.WRITE_SETTINGS"
        val WRITE_SMS = "android.permission.WRITE_SMS"

        @Deprecated("")
        val WRITE_SOCIAL_STREAM = "android.permission.WRITE_SOCIAL_STREAM"
        val WRITE_SYNC_SETTINGS = "android.permission.WRITE_SYNC_SETTINGS"
        val WRITE_USER_DICTIONARY = "android.permission.WRITE_USER_DICTIONARY"
        val WRITE_VOICEMAIL = "com.android.voicemail.permission.WRITE_VOICEMAIL"

    }

}
